language: android

before_install:
  - yes | sdkmanager "platforms;android-27"

android:
  components:
  - tools
  - platform-tools
  - build-tools-27.0.2
  - android-27
  - extra-android-m2repository
  - extra-android-support

jdk:
- oraclejdk8

branches:
  only:
  - master
  - develop

before_script:
- openssl aes-256-cbc -K $encrypted_73202214b473_key -iv $encrypted_73202214b473_iv -in secring.gpg.enc -out secring.gpg -d

script:
- ./gradlew clean build uploadArchives

env:
  global:
  - secure: J/jWzq+ey4xiTbNWbbXc+vHl/oJyAGE0Lj+QBC5xknjWEwUopXpq7MhAbtXvydiiiThYgoO9L7nY8PP3n9/rdDiex6n49LGDAMo1R1nodVsyasjcuTtpIbPWrarDWmnbuQ+X36VSdciEl2wiipUSz3dI3jrMnifZYbKFIdrQ/m6EFFPvdOU0Orayc/3GNZ6laqaYgcaBVguzjzlZKVEPNOCpNt3JLhmXz2ahXV0I3Rap8H3uCgWMu4D9EdpPU5pcheitLv0EcwHlEwqYYfz00lV9ouB6fMEEfLkLzeHHInwP5nFRUs35Frmwz969dt80pLGwjt9es+kUS9WsbgWAHclPM5xNTeghPaIZRq1JtKBD6y7akR5Oq0hrksuD7NIK8G170zum3oieOqGQv/8tgSAiTYDgQfZTHVW4DFyayWAApJqWNVGLl1oFyXSFNMPfDhiD3R+OcPt+8Kb6GCZW4fbSheJ9z19YG2kKHJbjIRfNiF2HDfdU/kmIFtUcuQGy6WYaVt7MVYMLlQeKWY3cuedvdygpOL/8uAl8mH0GDRwbVrj2gq0BwTZeBmSqYoDO9mMipgyJWE+T3sWBDdyQjHbsIyT6QIM7aR0NvwXrm6y+mHB842DfZup67szbHjPe75Vlvo92CehEXWG4s8wf9NQvtZ0J7/oQ7LS49yxpQ5U=
  - secure: lLBDMIkb8Ueky41n6S3xYCoDP9k7ROv2HTdFsqWHNE/u5wA01A/V4UIpm0Hzhu2m1S44r5tDPh2JEslaFWFlJedkLU+J/9cDZCW2OLtIJbxsO7Jh9G38RJxZ/nF2nbG2dqdKeTJifJ/W5Wqn0Ph1MIRrRBG6pQq8gWvoP7edc7L3t2UCbKELnndhTD5QMFgC++q5b6FZw0KJ9ykBx1TGkEPw12Q1vHZo100WVHSuZBcYnrChrVA/yZeXkLDSiLOe8PQ0EWeaMCgbA847YtYXzvTclVXDSmiW/QUSV2IJlyuE6+r1j5iwzjfoUb/bQdOVMPRooo0ZLOzPT7vbvl4S6PPaxqIpgVPdCSx9mdc1h70CHnBTcMu2KADvlelwQOTySxj++k6iZmKNV8aIKZS4PEc0DOglhepjMwfbEQ6aOQDn2WMmMfSwTwdG1VZltvAK90FKo/sDG071Z7QbhZdWlUmA3UiKNFHnDFxX7FzhZrCqd0UCQKte2X0fduOjs2bdjlhotM9vGi2BK9HZUacNxObxplpPxYnnGxYdGJP999qeKb4JLDXBe/BHTE9YaM0TjXydnHn2L+efrWdGygauFVe3ngiwSSUR5WQIRLsP2P3Rc/53Xe+rAcQOBmwyfrgYxbovEzczePZTb6i7Sg4Kgc9airjYYvz/OhbYV9FvgMI=
  - secure: avPDxLxCoEC4hEagHGOr8vr7Zu8bN4688fxMD2O0b+MJ4q5t61nC3iBBbB6cfpmxKDimSZkzli6wCi3escQK9CLCnjonAxoWp/kO3/yxyyq6+Y1iS2a4ULB6r6rCsN5LrP5wWTtiM29yW4aQgsM7nlgLjettdkRPGSGeSK9bK25Y0y/JLiA59JbdV9jIE1IkSd3zEV8wkliBhqM5oGRzCr7nA3VpLMNK491Q9Hplgi7vPeYiJ4YO2lzkGRMLdMFO6VrSAjYn2SJg+0sPlUcJ6jxDCicZb79/2fRq2+Wu7wNRD4RvHN4XMw3YzT70hj6z4oYtzF/75ezBV7DvY9cc2ImRNuGmlXTvRDbk5zZxey+xDNSgDNp4xUqLkuIujfggcpTPBL4b4TeZBll0NcDTjSEBlymMhU5m+OT1lyNmwZl8qC4X/zLe6Ysh5mwupeju9e/DRol7heP7yKNVIm8EyNrEenmUJPMOxbc7RAUhY+z1NL71zelkKwxGuTssnvNXyBsaMHLsT2QDr3xIPqb5NLn36a3NIeG6aLd0O4gPfFfa40AdojuyTmeudFZuuCTgKH/bNi5ad2VJuNKVwNmswiBiWp3Jl/Q9T4fHhw6+WbsU1YMC22s4DFWR1SAwAnWSQ+dbkzE5YuA/1nFm8+kdcKFQmlsqMYhG5BbQEx9hDEw=
  - secure: esqa3DHi1fSH/OFVKJIzXAlK311VZoSqcsAGNjVeGgovdf35XL4K3zhBD67Pul5QZtwCzPbaag2vzuMSnvQO6WwZBJtEEe3jpeL79+TWPbXPUT6+uIY3I2lt5PHzjktpBmNOCgrhWTWu6GwcR8UGIq0Faa4nrEeVgmJQz0vWvJ/VMoNphlQxUWbs+Qdl1H1DQscZ/VVgALuEhlhcbh65JzTaXvmOtQej9dycFjri+uoXDMVYWEKLHCCqZm7AxOtvujzZQHlhWTG68s7h84GtD1H969/ihL+Flc70AoeRcM9OFnp8DYePVneA5QFLbuc2BfMSwP6wxcTEeNLpBgt5Nwqomaj5m/vp+Ab4kP5Popvd7b/zX3410ei03MmtrBS+uQi5jeN0TYRjGzjK6bCYsqOnGMIE3EReldDWbSktBCb++ueOXatspu24RwyA5CnvpPqc2Kze5gWEU0eglDWgJOPq+VvU/1GxDu2G91iTJfF3LzPUNCSzaI9NMyguD5rxVQcMJaGJBgLy2da6BNlWdHtVdWLkCWYulV8ApgCkkygtb5MCJVopYtyV3xRuIvcfW2oDStVTm7dR8b+sNtvGA2dFUhKgTTTxkHxnDzosSyBzamkOzd7eYW1sh846Z5apaKz/bXlzpZf3FXXTcETNTT74RClShuPeA4Z1EEHlPC4=
  
cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle
