language: android

android:
  components:
  - tools
  - platform-tools
  - build-tools-25.0.2
  - android-25
  - extra-android-m2repository
  - extra-android-support

jdk:
- oraclejdk8

branches:
  only:
  - master
  - stable

before_script:
- openssl aes-256-cbc -K $encrypted_d6b6c7dad457_key -iv $encrypted_d6b6c7dad457_iv
  -in secring.gpg.enc -out secring.gpg -d

script:
- ./gradlew clean build uploadArchives

env:
  global:
  - secure: urJGasqUKAT0Iu4DNuSN06btyQob84dxM3MYxwiJdPMEayi+scUGig8PVGgYV1ZSzgpthQ2iuIZZ6Z+YMM2RVlhwsJDv889+ScXgY3kk6PxTsgWUkZ9DLjKk5DUv50C5gFu1Ngx02bnk/CVGST67qbLR76vMAEw53TEQ0bbYli8Mkm+VDpfxLQS9JjVHkwrA4EWToWyIb19U/x2ioyXUaLluF3lH3SxPFwDsnvBCPUjIsQV0U64VN4+N866WwRVSeJYM/oDLZO/rWHeKRS7MgoT20xc4aVOKHIEuJDlg13BQ8hKMQ0DLAmlHm+UArs/JF6fJeFC/ECncNtkcede12NohLc/qPaQDz7uFMic0Ul8tFv/bRpAvTEZ3OxzYHwd/EYwpqajzwTuZox0hsX6Ei0crpRj/8Ghmq9lKInTDF77+8KyUKxeqNcGKqUY4EpTUFurxzXDjU6REPsr3Wd+3CXSgmEPTJp3Zc4SOHspV/np8NvD6zzFCG8ZT9UJyLVO8I3pi/mF6yISrg7g1iDZri0YFNwVazgW6DPseNyr4Y5YSLurau3t3TmFM4jYcGsI2+qYRU6HVA0gglcqCxlXVgxzjUn6LfPsrCncUoFiTfnsTYo9Eq4I8SVmj88Wjr5UeW1Xn6HqK3iPVfbtcx/NV6uHbLd25YSMgO5eOvC72BN4=
  - secure: SmVsGp6JT7jl1I1ZLyx+xBke7hQp63VEz3TUlOb2iiqTZoOokxHbLeUNqLaDBwcea6kM2S4H+V2pUd1Tu/hIkRGZLe3Xuk+92fX/b5mMdsKwqAf2XmUUMJmWNLPrkmaM1pZlMoTFveNpPBR/F1jOQPNO1UBheYAFw4VdgVKHf29EYzGhu7RYifih4wz6IVeH+ARxeOmJtxOXqUihQMvF/6XJ3c0tTh34Ijgiok/tdjUDvtNXfGXK+5wih07OLPhrd+6vWzY4cC1JU0rbt9RRxUmfkxbYShYjVw386gkqQIPHLb3IZS80IciO7xa27xz1I6Q/6OMtXRV8By/eS5cGJX088xEDcgoAkQH4dyetL2970UPTH2sVcpoC2qrvl+GLirnaM2H51Rp2C8j66KHQYHwpUX7BpffixkksfiM/OBPmXeCJwOTEM6KjiBeqZL3EDTEm84id9zfOc3e66qOlhaj3Nd7W56mNmu9ryYBomGI5UhNUCpZgVjhqvDxxojcjXKU++disPnb8cbpU1LIz03zBGJ+jXTbDTG8X0NpE12WkcwPfOIhKnVkgWHgOyoR+VCiFnyD+sxBrgmR0Iac5esKXICFA+ntfmJP8yhZNlyNwX2lkZl7cTWVQoJD0ljGk8q/st11CiB6OrMwjKq0+Mo9mVwO4lrxnbauGa82DJjc=
  - secure: rL2YlQ2fgqXWdwiqvIO60B2P3VvEom5BIJRu+gJ4VGo7U+w0I7A8Q0D0zO4Fubj3w9ZwiFojFxmKkA51kjm7lcwIefQFon8NPkPwqQ3Rz+66JtYbsPoxAj/o+WfJ+472NEbD7YqUNHo7GFj2RYpUCBftQu7QGmDUtRgE8REZjQ6A7LaPFXLNa4CNWekm0Czop2ErlVeRslFTlBS9DegM5Jbj3dawJgwz9oVzLj4UMSTeGusvcmxpqCoc2/CXYjA2Jr5O1GyUok1vrlxXkx+0294MygHqC9rnpFr0voP8SogdwEig+eWHIteHez3uYowKaBNDmpncE9sbxCJ+phkQGHoiv46L0dc29toeFcsBSbVVzC9+Npw6tcFGI8efxAXx2MvXSTxlb5ulBOtHxx/OJamjk4T/LEruPXg8RES68ymb/HAAWJqKDpBK3m/3laOLE5Xtc7Vb/w02CIaL3N7RM+7RHCCVFd4toC/PppilGZSZ2ywAviOpvekrBdMFDlwcXVUHwTtQeu3HWsQwhluyNJVQrGrR4NAzUfbAA9v2PZfcSfGGTxd+msj5dv8ip473J3CZh1gdTTVXce3LX/viYYaxF0vxvcq0xSl5N5PpWMhfzCQE2Nu63X8MtqZ+ZIEoc7B5mbP97CC3geIsxP0TAN8FVumyKp/55lIM2cIwrrA=
  - secure: AKF4+wa3sbowuwf8mlcmoUReqgl2cj9MMBUo2vZO+dMotyPZ2UKVH8fLJdvvIPLMYPZNkiBRKtaYdpRpMsbvs/a6Frdc13hoqZxxClvomJJ4NlFj+l6qQmOwrrzv3UCiHk2vUtf1sVZ30EvjGULL5+DWgawU/0yQAguQQaNCXJkxZr+t9qFzo7Os4smbtMJeoSwMsNh6oZtHVJNhezBUxmGet414ata29taaOc1jUZwr+3tAmEH2PX93Kd0Ie2mv4ZCgpZs6h3K3PUq1pEk4KjWd/57rywVGaAirsDa3pq9RILGBNc00fkLQ+ipjPOXL/6WAd/tohpsvr9iiclEnystumnztTRIYJs5SkNwY/ks4KA5PEumd+KtbyaNQ7iduxm3mUZriz6nCgFtqwvP1k9lHZPv2Yjc3mYv07hYmXDIq2LQhrJvMTIP4jVkMXPsF67kX/z1+3NZITnIhSL6y4iT35N+1N30aACgoWh0u7+Jd868+VMWorJZfV1mtfAxvcF/JpEdxIKIGlPqo9gx+pbouzCzhc2R5jjKzoHXT6Wi9zTyr7E6mMIGDLPM6igcCUUx3/2TQznvBNaqBYJFzx4NK5s8QcVIMM6O8RMRPCJoEfXreGxmIzGNL2molLQ/iXbT+arXLwrECUIyjUp+W4wgvnk3o4m7FPsPZKW1lzBE=
  - secure: bvnKRpXrggXTez5qKr4SfmuKIupFFjRdxZlBKJR19KD4hapuoWIsqn323nHYK5tNaLIj2TkZeZA/CcuHT67eNSuPFxC+I+ipJmGN2zZq8F5c6de17kzV0ATyLuoWOKJrtLc5myjtyPIVEGISiEb1+tplhEyINfbI+yU8Dz+T81kpMyA7gc93EK1ssRFNKFFiU8QD3uX4nGiyKBaXvDcmkCTXMvqYeLxfAGPJ+G6t8sKlqKPubYYaRYQck2LhU18HdUzMT0NL91l5WSXUjvIiXBcF3SCSr91JE59ZPZMAFXZGTbfuIXOLV4FhU8OFDs0LhYrIHKxMpt82EA6D+BtevT/6Ny4CoGoMIrLMHySgDLgfWfxOdKl7A5exy14pHCZHg3RVnFaOF5rzBF5q+1KsDC3jwdktTueJoBZAlhACtQCs1sxyW3u760vDx8s5T5+kPkA2ullXSGtA7r/8Dsp94RjcguqTgbv3YSNR2kev7RoZ9hXh8X/Kp3wc5/nB9S04RjGCcLoBI6ttIYTYPW3QPREaHEfzJaZMklXzmakTtNQerlDNVp3IB2G55Nwc9ya1Zh5ivDlRUc/93fioAEazI5MgWEG2fZRSgbXWL4onImVJaPJFHz6cwOZ4tXF7+ALplLBYSgXl2l6VFk7sFdK0TuqVBRf+rnwci5jpDZ34oSk=

cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle
